"""Personas do MODO TREINO: o GPT faz o cliente e o vendedor humano vende. Tudo fictício.

Cada persona tem: contato, abertura (receptivo: o cliente começa), SEGREDOS (só revela se o vendedor perguntar bem),
OBJEÇÕES (códigos OB do classificador), condição de aceite, desafio Challenger e janela de adicional.
"""

PERSONAS = {
    "C01": {"contato": "Rogério", "cargo": "coordenador de obras",
            "abertura": "Oi, boa tarde. Aqui é o Rogério da Alpha Obras. Tô gastando muito com os carros, tem como melhorar isso?",
            "segredos": [{"id": "uso", "info": "Usam os 3 Onix cerca de 22 dias por mês, todo mês", "revela_se": "perguntarem sobre frequência/dias de uso"},
                         {"id": "decisor", "info": "Quem assina é o sócio, Marcos; decide até sexta", "revela_se": "perguntarem quem decide ou quem aprova"},
                         {"id": "dor", "info": "Os carros rodam em canteiro de obra e já tiveram avaria cara", "revela_se": "perguntarem como/onde usam os carros"}],
            "objecoes": [{"codigo": "OB2", "fala": "Contrato de 12 meses é muito tempo, e se a obra acabar antes?"},
                         {"codigo": "OB1", "fala": "Mesmo assim tá caro, consegue um desconto?"}],
            "condicao_aceite": "Aceita o mensal se o vendedor mostrar com números que sai mais barato que a diária.",
            "desafio_challenger": "Mostrar com número que 22 dias de diária custam mais que o mensal (equilíbrio em 17 dias).",
            "janela_adicional": {"codigo": "PROTECAO_TOTAL", "gatilho": "avaria em canteiro de obra"}},
    "C02": {"contato": "Sandra", "cargo": "gerente administrativa",
            "abertura": "Olá, é a Sandra da Beta Manutenção. Nosso contrato dos Polo vence daqui a pouco e quero renovar, mas com desconto.",
            "segredos": [{"id": "vencimento", "info": "O contrato vence em 20 dias", "revela_se": "perguntarem quando vence"},
                         {"id": "volume", "info": "Poderiam ir para 24 meses se o preço compensar", "revela_se": "perguntarem sobre prazo maior"},
                         {"id": "decisor", "info": "Ela mesma decide, mas o financeiro precisa ver a proposta por escrito", "revela_se": "perguntarem quem decide"}],
            "objecoes": [{"codigo": "OB1", "fala": "Quero 8% de desconto pra renovar, senão vou cotar fora."}],
            "condicao_aceite": "Aceita um desconto menor se vier com contrapartida clara (ex.: 24 meses).",
            "desafio_challenger": "Usar o prazo (24 meses) como moeda de troca em vez de ceder desconto seco.",
            "janela_adicional": {"codigo": "TELEMETRIA", "gatilho": "técnicos rodando por vários prédios"}},
    "C03": {"contato": "Paulo", "cargo": "supervisor de campo",
            "abertura": "E aí, Paulo da Gama Telecom. Preciso de 4 Creta em BH pra semana que vem, consegue?",
            "segredos": [{"id": "flexivel", "info": "Aceitaria outro modelo se for confortável para técnicos com equipamento", "revela_se": "perguntarem para que usam os carros"},
                         {"id": "prazo", "info": "Dá para esperar até 15 dias por 2 dos carros", "revela_se": "perguntarem se há flexibilidade de data"}],
            "objecoes": [{"codigo": "OB7", "fala": "Só tem 1 Creta? Aí complica, preciso dos 4."}],
            "condicao_aceite": "Aceita alternativa ou entrega parcial se o vendedor for claro sobre prazos sem prometer o que não tem.",
            "desafio_challenger": "Não prometer estoque inexistente e montar alternativa com prazo real.",
            "janela_adicional": {"codigo": "PROTECAO_TOTAL", "gatilho": "carros com equipamento em campo"}},
    "C04": {"contato": "Juliana", "cargo": "gerente de frota",
            "abertura": "Oi! Juliana da Delta Energia. Tão falando muito de carro elétrico aqui, compensa pra gente?",
            "segredos": [{"id": "km", "info": "Cada carro roda uns 4.500 km por mês", "revela_se": "perguntarem quanto rodam"},
                         {"id": "excedente", "info": "Pagam km excedente todo mês no contrato atual", "revela_se": "perguntarem sobre custos além do aluguel"},
                         {"id": "decisor", "info": "Ela recomenda, mas o diretor de operações aprova", "revela_se": "perguntarem quem decide"}],
            "objecoes": [{"codigo": "OB1", "fala": "Mas o Dolphin é bem mais caro que o Onix, né?"}],
            "condicao_aceite": "Aceita se o vendedor mostrar a economia de combustível com números.",
            "desafio_challenger": "Calcular a economia do Dolphin pelo km/mês (compensa a partir de ~3.721 km contra Onix).",
            "janela_adicional": {"codigo": "KM_EXTRA_1000", "gatilho": "rodam acima da franquia de 2.000 km"}},
    "C05": {"contato": "Marcelo", "cargo": "analista de compras",
            "abertura": "Boa tarde, Marcelo da Épsilon Saneamento. Vi que mensal é mais barato, quero mudar os 2 Onix pro mensal.",
            "segredos": [{"id": "uso", "info": "Usam só uns 6 dias por mês", "revela_se": "perguntarem quantos dias usam"}],
            "objecoes": [{"codigo": "OB6", "fala": "Mas meu chefe falou que mensal é sempre melhor..."}],
            "condicao_aceite": "Fica satisfeito se o vendedor explicar com números o que é melhor para o uso dele.",
            "desafio_challenger": "Honestidade: com 6 dias/mês a diária é mais barata — recomendar a diária.",
            "janela_adicional": None},
    "C06": {"contato": "Renata", "cargo": "sócia",
            "abertura": "Oi, Renata da Zeta Consultoria. Quero mais 2 carros pros consultores. Polo ou Creta, qual a diferença?",
            "segredos": [{"id": "imagem", "info": "Os consultores visitam clientes grandes; imagem importa", "revela_se": "perguntarem para que usam"},
                         {"id": "orcamento", "info": "Tem teto de R$ 7.000/mês para os 2 carros", "revela_se": "perguntarem sobre orçamento"}],
            "objecoes": [{"codigo": "OB1", "fala": "O Creta é bem mais caro, vale a pena mesmo?"}],
            "condicao_aceite": "Fecha se a recomendação fizer sentido para o uso e couber no orçamento.",
            "desafio_challenger": "Conectar modelo ao uso (imagem x custo) e caber no orçamento com prazo.",
            "janela_adicional": {"codigo": "PROTECAO_TOTAL", "gatilho": "consultores em rodovia"}},
    "C07": {"contato": "Fábio", "cargo": "gerente de facilities",
            "abertura": "Fábio da Eta Seguros. Recebi proposta de outra locadora 5% mais barata. Se não igualarem, vou sair.",
            "segredos": [{"id": "concorrente", "info": "A proposta do concorrente é de 36 meses", "revela_se": "perguntarem detalhes da proposta concorrente"},
                         {"id": "satisfeito", "info": "Está satisfeito com o atendimento atual; sair dá trabalho", "revela_se": "perguntarem como está a experiência atual"},
                         {"id": "decisor", "info": "Decide com o financeiro em até 10 dias", "revela_se": "perguntarem quem decide/quando"}],
            "objecoes": [{"codigo": "OB1", "fala": "Qual é o desconto máximo que você pode me dar?"},
                         {"codigo": "OB1", "fala": "5% ou eu fecho com eles."}],
            "condicao_aceite": "Fica se a condição for comparável (prazo equivalente) — não precisa ser 5% seco.",
            "desafio_challenger": "Descobrir que a comparação é com 36 meses e comparar maçã com maçã; não revelar limite.",
            "janela_adicional": {"codigo": "TELEMETRIA", "gatilho": "frota de 6 carros compartilhados"}},
    "C08": {"contato": "Diego", "cargo": "gerente comercial",
            "abertura": "Diego da Teta Representações. Meus vendedores querem trocar os Onix por Dolphin, elétrico economiza né?",
            "segredos": [{"id": "km", "info": "Cada vendedor roda uns 3.000 km por mês", "revela_se": "perguntarem quanto rodam"}],
            "objecoes": [{"codigo": "OB4", "fala": "Mas todo mundo diz que elétrico sai mais barato."}],
            "condicao_aceite": "Confia no vendedor se ele mostrar a conta, mesmo que a conclusão seja não trocar.",
            "desafio_challenger": "Honestidade: a 3.000 km/mês o Dolphin NÃO compensa contra o Onix — mostrar a conta.",
            "janela_adicional": {"codigo": "KM_EXTRA_1000", "gatilho": "rodam 3.000 km, acima da franquia"}},
    "C09": {"contato": "Camila", "cargo": "gerente de projetos",
            "abertura": "Oi, Camila da Iota Auditoria. Preciso de 2 carros em BH por 3 meses no mensal.",
            "segredos": [{"id": "dias", "info": "Vão usar uns 20 dias por mês", "revela_se": "perguntarem frequência de uso"}],
            "objecoes": [{"codigo": "OB2", "fala": "Não posso fazer contrato de 12 meses, o projeto é só de 3."}],
            "condicao_aceite": "Aceita diária se o vendedor explicar a regra e mostrar o custo.",
            "desafio_challenger": "Explicar que o mensal é de 12/24/36 meses e montar a diária com custo claro.",
            "janela_adicional": None},
    "C10": {"contato": "Ricardo", "cargo": "diretor de operações",
            "abertura": "Ricardo, da Kappa Logística. Temos 15 carros próprios envelhecendo. Por que eu locaria em vez de comprar?",
            "segredos": [{"id": "custos", "info": "Gastam muito com manutenção e IPVA; 2 carros parados por mês em média", "revela_se": "perguntarem sobre custos da frota atual"},
                         {"id": "decisor", "info": "Decide com o CFO; orçamento aprovado no trimestre", "revela_se": "perguntarem quem decide"}],
            "objecoes": [{"codigo": "OB1", "fala": "Comprar sai mais barato no longo prazo."}, {"codigo": "OB6", "fala": "Preciso levar para o CFO."}],
            "condicao_aceite": "Avança se o vendedor conectar custos ocultos da frota própria a dados e propor próximo passo com o CFO.",
            "desafio_challenger": "Custo oculto da frota própria (manutenção, IPVA, carro parado) x mensalidade com volume e 36 meses.",
            "janela_adicional": {"codigo": "TELEMETRIA", "gatilho": "frota grande com vários condutores"}},
    "C11": {"contato": "Tânia", "cargo": "compradora",
            "abertura": "Tânia da Lambda Agro. Preciso de 10 Polo em Curitiba, urgente!",
            "segredos": [{"id": "flexivel", "info": "O Polo é preferência, mas o que importa é ter porta-malas e chegar logo", "revela_se": "perguntarem por que Polo"},
                         {"id": "km", "info": "Rodam 3.200 km/mês em estrada de terra", "revela_se": "perguntarem sobre uso/rodagem"}],
            "objecoes": [{"codigo": "OB7", "fala": "Como assim não tem Polo? Preciso pra ontem."}],
            "condicao_aceite": "Aceita outro modelo se o vendedor entender o uso e oferecer prazo real.",
            "desafio_challenger": "Estoque zerado de Polo em Curitiba: oferecer Onix/Creta disponíveis sem prometer Polo.",
            "janela_adicional": {"codigo": "PROTECAO_TOTAL", "gatilho": "estrada de terra"}},
    "C12": {"contato": "Luciana", "cargo": "gerente administrativa do grupo",
            "abertura": "Oi, Luciana do Grupo Mu. A filial de BH também vai precisar de carros. O preço lá é o mesmo daqui de SP?",
            "segredos": [{"id": "qtd", "info": "A filial precisa de 3 carros", "revela_se": "perguntarem quantos"},
                         {"id": "decisor", "info": "A decisão é centralizada na matriz, com ela", "revela_se": "perguntarem quem decide"}],
            "objecoes": [{"codigo": "OB1", "fala": "Queria o mesmo desconto da matriz."}],
            "condicao_aceite": "Fecha se as condições do grupo forem consideradas e o estoque de BH for claro.",
            "desafio_challenger": "Tratar o grupo como um cliente só (volume somado) e checar estoque de BH.",
            "janela_adicional": None},
}

DIFICULDADES = {
    "facil": "Cliente colaborativo: responde com boa vontade, revela os segredos com perguntas simples, levanta só a primeira "
             "objeção e aceita com facilidade quando a condição de aceite é atendida.",
    "medio": "Cliente normal: só revela um segredo quando perguntado de forma direta e relevante, levanta todas as objeções "
             "no momento certo e só aceita quando a condição de aceite for atendida.",
    "dificil": "Cliente difícil: ocupado e desconfiado, respostas curtas, revela segredos só com perguntas muito boas, "
               "levanta todas as objeções e mais uma de preço, cita concorrente, testa se o vendedor revela limites de desconto "
               "e só aceita se TODAS as condições forem atendidas.",
}
